version: "3.8"

services:
  service:
    build: .
    shm_size: 2gb
    container_name: vendor_service
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000" 
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.devs
    depends_on:
      - db
  
  db:
    build:
      context: ./scripts_container/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    volumes:
      - postgres_data:/var/lib/postgres/data/
   
  
volumes:
  postgres_data:   
