version: "3.8"

services:
  service:
    build: .
    shm_size: 2gb
    container_name: vendor_service
    command: >
      sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000" 
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.devs
    depends_on:
      - db
  
  db:
    build:
      context: ./scripts_container/
    environment:
      - POSTGRES_USER=bruno
      - POSTGRES_PASSWORD=bruno
      - POSTGRES_DB=vendor_catalog
    volumes:
      - postgres_data:/var/lib/postgres/data/
    ports:
      - 5433:5432
   
  
volumes:
  postgres_data:   
