# Generated by Django 3.2.7 on 2021-09-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='products',
        ),
        migrations.AddField(
            model_name='vendor',
            name='products',
            field=models.ManyToManyField(to='vendor_app.Product'),
        ),
    ]
