# Generated by Django 3.2.7 on 2021-10-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0002_auto_20210928_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='cnpj',
            field=models.CharField(max_length=14),
        ),
    ]
